### ISSUE TITLE
Any chance it can support orgmode?

### ISSUE THREAD

**Issue by mittenchops** [Flask-FlatPages/Flask-FlatPages#12]
Super cool extension.

**Comment by oneyb** [comment]
Dear Simon,

I am sorry to dig this one up. I implemented a rudimentary fix to handle my emacs org-mode files with flatpages [(app.py)](https://github.com/oneyb/oneyb.github.io/blob/master/app.py) The solution is part of my even more rudimentary static webpage source. It wasn't as trivial as suggested here because the header is separated from the body when being parsed. Thus, the org-mode header needed a simple translation to yaml, which for the useful part (title, author, date) is one-to-one.

Anyways, I would consider working on a pull request, but I would appreciate some guidance on where changes would be welcome and what kind of tests you would appreciate. 

Cheers,
Brian

**Comment by SimonSapin** [comment]
I am not maintaining this anymore. Deferring to @playpauseandstop.
